WIP: Client authentication
FortinoSandoval/MarketOrganizer.Client pull request #1
Opened 2019-04-02 21:27 UTC by FortinoSandoval

router and some components were added

2019-04-02 21:47 UTC, AngelMunoz requested changes
te dejo unos comentarios, en este caso trata de hacer los fixes en el mismo pr, no pasa nada si te tardas unas horas/dias mas en meter los cambios el codigo no se ira a ningun lado

2019-04-02 21:47 UTC, AngelMunoz commented on src/app/home/home.component.ts
> +  ngOnInit() {
si no tienen logica en el ngOnInit, es preferible que no lo pongas, menos imports === menos codigo que se descarga al cliente

2019-04-02 21:47 UTC, AngelMunoz commented on src/app/login/login.component.html
> +    <form #myForm="ngForm" class="login-form" name="form" (ngSubmit)="myForm.form.valid && onSubmit(myForm.form)">
trata de evitar nombres como `myForm`, se mas descriptivo con los nombres, loginForm es bueno, que se note la intencion del nombre y que representa dicho nombre

2019-04-02 21:47 UTC, AngelMunoz commented on src/app/register/register.component.html
> +      <form #myForm="ngForm" class="register-form" name="form" (ngSubmit)="myForm.form.valid && onSubmit(myForm.form)">
lo mismo que para el login

2019-04-02 21:47 UTC, AngelMunoz commented on src/app/register/register.component.less
> +#register-page {
trata de limitar el uso de ID's y usa en su mayor parte clases de css

identifica por ejemplo cuantos elementos pueden ser estilizados como una pagina y mejor crea una clase pagina para que puedas ir modificando esa 
por ejemplo
```css
/* app.css */
.page { /*.../* }

/* register-page.css */
.page.register-page { /*.../* }
```

2019-04-02 21:47 UTC, AngelMunoz commented on src/app/login/login.component.html
> +<div id="login-page">
trata de no usar ids para estilizar secciones completas de paginas usa clases, abajo de dejare un comentario.

respecto al HTML, usa elementos semanticos de HTML es decir
```html
<article class="page login-page">
  <header class="login-page__header">
     <menu>
       <a>mi opcion</a>
     </menu
  </header>
  <main class="login-page__main">
    <mi-componente></mi-componente>
   <!-- mas componentes etc -->
  </main>
  <footer class="login-page__footer">
   <p>Cosas del footer si es que existe el footer</p>
  </footer>
</article>
```
no tene que ser ese layout exacto, pero intenta usar  elementos semanticos, hace mas legible el contenido y en ocasiones mejora la legibilidad para lectores de pantalla

2019-04-02 21:47 UTC, AngelMunoz commented on src/app/register/register.component.ts
> +  canRegister: boolean = true;
en casos como este no es necesario especificar el tipo de dato ya que es obvio con la inicializacion
especifica el tipo de dato con objetos, donde no es Obvio cual es el contenido
```suggestion
  canRegister = true;
```
para evitar que le pongas `any` a todo usa las interfaces para que tengas auto-completado y prevengas bugs mas adelante
```ts
export interface MyModel {
  email: string;
  nombre?: string; // opcional
  password: string;
}

class RegisterComponent implements OnInit {
  model: MyModel = { email: ''; password: '' };
  canRegister = false;
}
```

2019-04-02 21:49 UTC, AngelMunoz commented on src/app/register/register.component.less
> +#register-page {
este no es 100% requerido, solo es una observacion para que no te mal-acostumbres a ponerle ID a todo

2019-04-03 13:57 UTC, FortinoSandoval commented on src/app/register/register.component.less
> +#register-page {
va

2019-04-03 13:57 UTC, AngelMunoz requested changes

2019-04-03 13:57 UTC, AngelMunoz commented on src/app/interfaces/user.interface.ts
> +  Password2?: string;
todos tus users tienen password? o solo los del registro?

no creo que `Username` y `Password` deban ser opcionales (por cierto no es necesario que los pongas con mayusculas, asp.net se encarga de transfrormarlos cuando los serializa/desesializa en el backend

Te recomiendo que tengas 2 interfaces en este caso
```ts
export interface User { // o UserDTO
  id?: number;
  username: string;
  // .. otras propiedades
}
export interface RegistrableUser { // o User si arriba usas UserDTO
    id?: number;
    username: string;
    password: string;
}
```
password2 te recomiendo que lo coloques solamente en la clase de registro ya que solo lo necesitas para validar antes de enviar el API no creo que te acepte 2 passwords o si?

2019-04-03 13:57 UTC, AngelMunoz commented on src/app/register/register.component.ts
> +    if (form.invalid) {
mejor deshabilita el boton de submit en el html :P
```html
<button [disabled]="!registerForm.form.invalid" type="submit">Sign Up </button>
```

2019-04-03 13:57 UTC, AngelMunoz commented on src/app/register/register.component.ts
>      this.matchError = false;
casi podria pensar que en esta parte estas sobre escribiendo el matchError

2019-04-03 13:58 UTC, AngelMunoz commented on src/app/register/register.component.ts
> +    if (form.invalid) {
esta solo es una sugerencia, no es necesaria (puedes resolver esta conversacion si quieres)

2019-04-03 17:04 UTC, FortinoSandoval commented on src/app/home/home.component.ts
> +  ngOnInit() {
el ngOnInit es necesario

2019-04-03 17:05 UTC, FortinoSandoval commented on src/app/register/register.component.ts
> +    if (form.invalid) {
creo que es doble seguridad, luego solo activas el boton en el inspector y sin esto, el formulario se manda

2019-04-03 17:05 UTC, FortinoSandoval commented on src/app/register/register.component.ts
>      this.matchError = false;
a que te refieres?

2019-04-03 18:10 UTC, AngelMunoz commented on src/app/register/register.component.ts
>      this.matchError = false;
que el match error lo pones como false si los passwords no cuadran, pero aun asi despues pones march error como false, no le hace falta ahi un `else` ?

2019-04-03 18:14 UTC, AngelMunoz commented on src/app/register/register.component.ts
> +    if (form.invalid) {
no es doble, igual puedes mandar el request con un postman :P y de nada sirve eso, las validaciones del cliente no sirven por eso siempre se valida en el servidor

2019-04-03 18:38 UTC, AngelMunoz commented on src/app/interfaces/user.interface.ts
> +  Password2?: string;
voy a mover esto a un issue

2019-04-03 18:38 UTC, AngelMunoz approved these changes

2019-04-03 18:42 UTC, merged